sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - ../create-react-microservice-test-scaffold/node_modules
notifications:
  email: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
  - yarn bootstrap
script:
  - yarn run build
  - yarn run test
  - ./build/integration-test.sh
after_success:
  - ./build/release.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
