dist: trusty
sudo: required
language: node_js
addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox
cache:
  directories:
    - node_modules
    - ../create-react-microservice-test-scaffold/node_modules
notifications:
  email: false
before_install:
  # Install the newest version of yarn since Travis containers have outdated yarn versions installed.
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Start a headless instance of google chrome for the integration test suite.
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  
  
install:
  - yarn install
  - yarn bootstrap
script:
  - yarn run build
  - yarn run test
  - ./build/integration-test.sh
after_success:
  - ./build/release.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
